### ISSUE TITLE
Create songlist for sprint 1

### ISSUE THREAD

**Issue by moonlightdrive** [cpeter256/soundstash#1]
Please comment with links to your 5 songs.

**Comment by JustinEwing** [comment]
Enjoy :)

https://www.youtube.com/watch?v=0lXEQdkOqJk
https://www.youtube.com/watch?v=0lXEQdkOqJk
https://www.youtube.com/watch?v=XlGh_okr5nI
https://www.youtube.com/watch?v=SBwK2s734DQ
https://www.youtube.com/watch?v=Cvu0Q4Cl7pU

**Comment by cpeter256** [comment]
Youtube is the low-hanging fruit, so I included links to alternative sources as well as tracks with unusual authorship and unicode metadata so we have more test cases.

...And there's six songs here since I got carried away looking for these edge cases. I guess that can make up for the double.

Zero Gravity from Immortal by BlackGryph0n & Baasik (Feat. Michelle Creber)
https://www.youtube.com/watch?v=LEnxIbwlNG8

Mirai Start by Mimori Suzuko, arranged by Delta Brony
https://deltabrony.bandcamp.com/track/mirai-start-pony-revolution-mix

Open My Heart from Starlit Flames by Ryazan (Feat. ヒロモト) 
https://www.youtube.com/watch?v=vhj5Qze00sQ

Kapow! by Vylet Pony
https://soundcloud.com/da5h-records/kapow

HEARTS♥RMX by Foozogz (Unattributed remix of Hearts Strong as Horses by Danial Ingram. Less of a technical edge case and more of a legal one.)
https://eqbeats.org/track/7189

Hooves Up High from Bass Rocket EP by Silva Hound (Feat. Rina-chan)
https://pony.fm/tracks/3516-hooves-up-high-ft-rina-chan

**Comment by risaisro** [comment]
Back and Forth by Haywyre
https://www.youtube.com/watch?v=V_8E0QXzebc

Smooth Criminal by Haywyre "reinterpretation" of Michael Jackson
https://www.youtube.com/watch?v=vLXS0EGwCZg

Lose It by Oh Wonder
https://soundcloud.com/ohwondermusic/lose-it

Sexualizer by Perturbator
https://www.youtube.com/watch?v=svyCX2qHWXU

Crystals by M.O.O.N
https://www.youtube.com/watch?v=AVblOqZBlJw
